### ISSUE TITLE
Fix "Event loop is closed." on :>restart/kill/f command.

### ISSUE THREAD

**Issue by IlexisTheMadcat** [SUPERMECHM500/MWSRam#12] opened 2020-06-08 19:57 UTC
```python
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    bot.run()
  File "C:\Users\thede\OneDrive\Documents\Python Scripts\Discord\MWSRam\utils\classes.py", line 205, in run
    super().run(self.auth.MWS_BOT_TOKEN, *args, **kwargs)
  File "C:\Users\thede\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 628, in run
    future = asyncio.ensure_future(runner(), loop=loop)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 661, in ensure_future
    task = loop.create_task(coro_or_future)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 429, in create_task
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000189C958DD30>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000189CD897910>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000189CF7CE400>
sys:1: RuntimeWarning: coroutine 'Client.run.<locals>.runner' was never awaited
```
Raised on `await self.bot.logout()`

**Comment by IlexisTheMadcat** [comment] 2020-06-09 03:37
Updated

**Comment by SirThane** [comment] 2020-06-09 14:07
Confirmed by getting the same error when running a test instance with one of my bot accounts. I will debug with PyCharm to try and identify what's causing this to be raised. It seems to be some background tasks are still trying to run in the event loop that don't get cleaned up when the loop is closed in `bot.logout()`. I'd think that the `logout()` would destroy tasks in the loop.

Something else to note is `RuntimeWarning: coroutine '<coroutine>' was never awaited`
This error is raised when an async coroutine is called like a normal function instead of awaited.

**Comment by IlexisTheMadcat** [comment] 2020-06-09 14:15
Possible solution: Before `bot.logout()`, for each `Loop` object, call its method `.stop()`
Source: [discord.ext.tasks.Loop.stop()](https://discordpy.readthedocs.io/en/latest/ext/tasks/index.html?highlight=loop#discord.ext.tasks.Loop.stop)

**Comment by IlexisTheMadcat** [comment] 2020-06-10 02:31
Update: Errors are now, for the most part, suppressed until most important to fix.
Setting tag to `wontfix` until a solution is thought of.

**Comment by SirThane** [comment] 2020-06-12 11:18
Errors were caused by the `while True:` in `main.py`. See notes in linked merges. `master` updated with changes. Production instance can now be restarted with `[p]f`. I would also suggest changing the auto pull behavior. I have some code that can be repurposed for this. I will prepare a branch for you to review.

**Closed as completed by SirThane** 2020-06-12 11:18 UTC
Labels: bug, wontfix
